# fly.toml app configuration file generated for marmitton on 2025-05-31T12:58:20-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'marmitton'
primary_region = 'ewr'

[build]
  dockerfile = './Dockerfile.fly'

[[vm]]
  size = 'shared-cpu-1x'
