# fly.toml app configuration file generated for marmithon on 2025-09-29T19:42:07-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'marmithon'
primary_region = 'iad'

[build]
  dockerfile = './Dockerfile'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
