# fly.toml app configuration file generated for marmithon on 2025-06-05T12:30:09-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'marmithon'
primary_region = 'ewr'

[build]
  dockerfile = './Dockerfile.fly'

[[vm]]
  size = 'shared-cpu-1x'
