name: ci
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.forgejo/workflows/renovate.yaml'
      - 'dev.toml'
      - 'renovate.json5'
      - 'README.md'

jobs:
  docker:
    runs-on: native
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set build tag
        shell: bash
        run: |
          echo "BUILD_TAG=main-${GITHUB_SHA:0:7}-$(date +%s)" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config: /etc/buildkit/buildkitd.toml
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: forge.internal
          username: ${{ secrets.GIT_USERNAME}}
          password: ${{ secrets.GIT_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            forge.internal/nemo/marmitton:latest
            forge.internal/nemo/marmitton:${{ env.BUILD_TAG }}
          build-args: |
            TARGETARCH=arm64
            TARGETOS=linux
