name: ci
on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: native
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set build tag
        shell: bash
        run: |
          echo "BUILD_TAG=main-${GITHUB_SHA:0:7}-$(date +%s)" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config: /etc/buildkit/buildkitd.toml
      - name: Login to git.internal
        uses: docker/login-action@v3
        with:
          registry: git.internal
          username: ${{ secrets.GIT_USERNAME }}
          password: ${{ secrets.GIT_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            git.internal/nrdufour/marmitton:latest
            git.internal/nrdufour/marmitton:${{ env.BUILD_TAG }}
